version: '3.8'
name: citest

services:
    app:
        container_name: citest
        image: citest
        build:
            context: ./
            dockerfile: ./deploy/Dockerfile
        ports:
            - 80:80
            - 443:443
        environment:
            PUID: 1000
            PGID: 1000
            DB_HOST: slipstream-db
        #            DB_PASSWORD: yoursecretdbpass
        volumes:
            - ./:/var/www/html
        #            - ./.env:/var/www/html/.env # .env File
        #            - ./teststorage/app:/var/www/html/storage/app # App folder
        #            - ./teststorage/logs:/var/www/html/storage/logs # Logs
        networks:
            - test_network
volumes:
    dbdata:

networks:
    test_network:
        driver: bridge

